import { motion } from 'framer-motion';
import { Shield, Lock, Eye, Users, FileWarning, CheckCircle2 } from 'lucide-react';

const securityPillars = [
  {
    title: 'Human-in-the-loop',
    icon: Users,
    desc: 'AI augments human decision-making, it does not replace it. Final funding decisions always require human authorization.',
  },
  {
    title: 'Deterministic Scoring',
    icon: CheckCircle2,
    desc: 'Evaluation metrics are strictly defined and consistently applied, eliminating the variability of traditional peer review.',
  },
  {
    title: 'Explainable AI',
    icon: Eye,
    desc: 'Every score generated by PRISM includes a detailed, citation-backed justification linking back to the original proposal text.',
  },
  {
    title: 'Secure Authentication',
    icon: Lock,
    desc: 'Multi-factor authentication and role-based access control ensure only authorized personnel can view sensitive research data.',
  },
  {
    title: 'Data Privacy',
    icon: Shield,
    desc: 'Proposals are processed in secure, isolated enclaves. Data is never used to train public models without explicit consent.',
  },
  {
    title: 'Audit Logging',
    icon: FileWarning,
    desc: 'Immutable, cryptographically verifiable logs track every interaction, evaluation, and decision made within the system.',
  },
];

export default function Security() {
  return (
    <div className="w-full min-h-screen pt-24 pb-20 relative overflow-hidden">
      {/* Background Elements */}
      <div className="absolute inset-0 z-0 pointer-events-none flex justify-center items-center opacity-30">
        <motion.div animate={{ rotate: 360 }} transition={{ duration: 100, repeat: Infinity, ease: "linear" }} className="w-[600px] h-[600px] border border-prism-accent/20 rounded-full" />
        <motion.div animate={{ rotate: -360 }} transition={{ duration: 120, repeat: Infinity, ease: "linear" }} className="absolute w-[800px] h-[800px] border border-prism-accent-secondary/20 rounded-full border-dashed" />
        <motion.div animate={{ rotate: 360 }} transition={{ duration: 140, repeat: Infinity, ease: "linear" }} className="absolute w-[1000px] h-[1000px] border border-prism-glow/10 rounded-full" />
      </div>

      <div className="container mx-auto px-4 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-20"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass-panel border-prism-accent/30 text-prism-accent text-sm font-mono mb-6">
            <Shield className="w-4 h-4" /> Trust & Transparency
          </div>
          <h1 className="text-4xl md:text-6xl font-bold text-glow mb-6">Security & Ethics</h1>
          <p className="text-xl text-prism-text-muted max-w-3xl mx-auto font-light">
            Built on a foundation of transparency, accountability, and military-grade data protection.
          </p>
        </motion.div>

        {/* Central Shield Visualization */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1, delay: 0.2 }}
          className="relative h-80 w-full max-w-4xl mx-auto flex items-center justify-center mb-24"
        >
          <div className="absolute inset-0 flex items-center justify-center">
            {/* Holographic Shield */}
            <div className="relative w-64 h-64 flex items-center justify-center">
              <motion.div 
                className="absolute inset-0 border-[3px] border-prism-accent rounded-full shadow-[0_0_30px_rgba(30,144,255,0.5)]"
                animate={{ scale: [1, 1.05, 1], opacity: [0.8, 1, 0.8] }}
                transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
              />
              <motion.div 
                className="absolute inset-4 border border-prism-accent-secondary rounded-full border-dashed"
                animate={{ rotate: 360 }}
                transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
              />
              <motion.div 
                className="absolute inset-8 border border-prism-glow/50 rounded-full"
                animate={{ rotate: -360 }}
                transition={{ duration: 15, repeat: Infinity, ease: "linear" }}
              />
              <Shield className="w-20 h-20 text-prism-text text-glow relative z-10" />
              
              {/* Encrypted connection lines */}
              {[0, 60, 120, 180, 240, 300].map((deg, i) => (
                <motion.div 
                  key={i}
                  className="absolute top-1/2 left-1/2 h-[2px] bg-gradient-to-r from-prism-accent to-transparent origin-left"
                  style={{ width: '150px', rotate: `${deg}deg` }}
                  animate={{ opacity: [0.2, 0.8, 0.2] }}
                  transition={{ duration: 2, repeat: Infinity, delay: i * 0.3 }}
                />
              ))}
            </div>
          </div>
        </motion.div>

        {/* Security Pillars Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
          {securityPillars.map((pillar, index) => (
            <motion.div
              key={pillar.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="glass-panel p-8 rounded-2xl border-t-2 border-t-prism-accent/50 hover:border-t-prism-accent hover:-translate-y-2 transition-all duration-300 group"
            >
              <div className="flex items-center justify-between mb-6">
                <div className="p-3 rounded-xl bg-prism-accent/10 border border-prism-accent/20 text-prism-accent group-hover:text-prism-glow group-hover:bg-prism-accent/20 transition-colors shadow-[0_0_15px_rgba(30,144,255,0.2)]">
                  <pillar.icon className="w-8 h-8" />
                </div>
                <div className="text-xs font-mono text-prism-text-muted/50 bg-prism-bg-alt px-2 py-1 rounded border border-prism-accent/10">
                  SEC_PLR_{String(index + 1).padStart(2, '0')}
                </div>
              </div>
              <h3 className="text-xl font-bold text-prism-text mb-3 group-hover:text-glow transition-all">{pillar.title}</h3>
              <p className="text-prism-text-muted leading-relaxed">
                {pillar.desc}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}
